In [1]:
import numpy as np

In [12]:
l=[1,2,3,4]#1d
a1=np.array(l)
a1

array([1, 2, 3, 4])

In [8]:
l1=[4,5,6,"sara","ineuron",True]

In [9]:
np.array(l1)

array(['4', '5', '6', 'sara', 'ineuron', 'True'], dtype='<U11')

In [13]:
a2=np.array([[1,2,3],[4,5,6]])#2d
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])#3d
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
a1.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
a1.shape

(4,)

In [19]:
a1.size

4

In [22]:
np.random.randint(2,50,(2,3,4))

array([[[45, 35, 36, 35],
        [38, 39, 13, 38],
        [30, 34,  4, 34]],

       [[20, 10, 19, 25],
        [ 8, 46,  9, 16],
        [13, 40, 28, 18]]])

In [23]:
np.random.randint(2,50,(3,4))

array([[22,  4, 10, 32],
       [15, 39, 42, 49],
       [39,  6, 13,  8]])

In [24]:
np.random.rand(4,4)

array([[0.62605357, 0.88942512, 0.7877605 , 0.64907428],
       [0.90838515, 0.67239987, 0.94121919, 0.51772943],
       [0.31443325, 0.34586785, 0.42193311, 0.51760967],
       [0.5563741 , 0.31593401, 0.26232285, 0.01410444]])

In [28]:
np.random.randn(4,4)

array([[-0.51454598, -1.70985138, -0.15832583,  0.54223315],
       [ 0.38637071,  1.11708878, -0.40316919, -0.2929704 ],
       [-0.99493103,  0.16802643, -0.05640591, -1.18465093],
       [-0.43321355,  0.42989136,  0.22175199,  0.46577128]])

In [31]:
np.random.rand(2,3,4)

array([[[0.45218753, 0.80709303, 0.16121927, 0.78773663],
        [0.98867093, 0.2062702 , 0.78712763, 0.07230669],
        [0.36904318, 0.7401524 , 0.18043773, 0.77252072]],

       [[0.96274539, 0.16546264, 0.48467979, 0.42509118],
        [0.94879108, 0.36118962, 0.84995902, 0.84204231],
        [0.29292029, 0.97340391, 0.85572366, 0.32099708]]])

In [36]:
a1.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [37]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [40]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [41]:
a2[[0,1],[1,2]]

array([2, 6])

In [43]:
a4=np.random.randint(2,90,(6,5))
a4

array([[39, 63, 64, 43, 23],
       [29, 42, 55, 69, 64],
       [ 3, 32, 74, 20, 42],
       [36, 37, 15, 52,  3],
       [36, 56, 12, 59, 63],
       [23, 75, 28, 18, 84]])

In [46]:
a4[a4>40]#condition filter

array([63, 64, 43, 42, 55, 69, 64, 74, 42, 52, 56, 59, 63, 75, 84])

In [50]:
a4[0,1]=9#reassignment with numpy
a4

array([[39,  9, 64, 43, 23],
       [29, 42, 55, 69, 64],
       [ 3, 32, 74, 20, 42],
       [36, 37, 15, 52,  3],
       [36, 56, 12, 59, 63],
       [23, 75, 28, 18, 84]])

In [53]:
a5=np.random.randint(0,3,(3,2))
a6=np.random.randint(0,3,(3,2))
a5*a6

array([[2, 1],
       [1, 0],
       [0, 4]])

http://matrixmultiplication.xyz/
    for visualization

In [54]:
a5/0#inf means infinty

C:\Users\Sharanya\AppData\Local\Temp\ipykernel_9480\538482321.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a5/0
C:\Users\Sharanya\AppData\Local\Temp\ipykernel_9480\538482321.py:1: RuntimeWarning: invalid value encountered in true_divide
  a5/0


array([[inf, inf],
       [inf, nan],
       [nan, inf]])

In [55]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.ones((12,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [61]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [62]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
a3.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [64]:
np.log10(a3)

array([[[0.        , 0.30103   , 0.47712125],
        [0.60205999, 0.69897   , 0.77815125],
        [0.84509804, 0.90308999, 0.95424251]]])

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [67]:
np.eye(5)#identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])