# Numpy-All basic operation

In [ ]:
import numpy as np
import array

In [4]:
a=np.array([1,2,3,4])#preparing an array with int format only
a

array([1, 2, 3, 4])

In [6]:
a.dtype

dtype('int32')

In [9]:
b=np.array([1,2,3,'sara','sudh',4+8j])#in this array creation we have add string,complex number so the data type is changed
b

array(['1', '2', '3', 'sara', 'sudh', '(4+8j)'], dtype='<U64')

In [10]:
b.dtype

dtype('<U64')

In [11]:
#2d array
np.array([
    
    [1,2,3],
    [1,4,6],
    [4,5,6]
    
       ])

array([[1, 2, 3],
       [1, 4, 6],
       [4, 5, 6]])

In [13]:
#3d array
np.array([[[1,2,2],[4,5,6]],[[2,3,4],[445,67,8]]])

array([[[  1,   2,   2],
        [  4,   5,   6]],

       [[  2,   3,   4],
        [445,  67,   8]]])

In [32]:
#4d array
arr4=np.array([[[[1,2,3],
            [2,43,5]],
        
           [[3,4,5],
           [3,5,6]],
           
           [[5,6,7],
           [2,3,5]],
           
           [[2,3,4],
           [3,5,5]]]])

In [33]:
arr4.ndim

4

In [16]:
#changing 1d array to 3d array
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [17]:
#changing data type
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
#accessing rows and columns from array
arr=np.array([[1,2],[3,4]])
arr[0][1]

2

In [19]:
#changing the array into matrix
np.matrix(arr)

matrix([[1, 2],
        [3, 4]])

In [20]:
l=[1,2,3,4]
#changing the list into array
np.array(l)

array([1, 2, 3, 4])

In [22]:
#array are mutable-so changing the values with the rows and columns
arr=np.array([[1,2],[7,8]])
arr[0][1]=345
arr

array([[  1, 345],
       [  7,   8]])

In [24]:
#slicing also done it
arr[0:100]

array([[  1, 345],
       [  7,   8]])

In [26]:
#even for loop is accepted in array
for i in arr:
    print(i)

[  1 345]
[7 8]


In [27]:
#fromfunction-by logic we have mentioned-create ndarray
np.fromfunction(lambda i,j :i==j,(3,3))#identity array is created with the logic we have provided

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
#fromiter function-create ndarray
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [29]:
#fromstring function-create ndarray
np.fromstring('1,2,3,4' , sep=',' , dtype=int)

array([1, 2, 3, 4])

In [36]:
#creating a ndarray with arange
np.arange(1,10,0.5)#(start values, end values,jump values)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [37]:
# creating nd array with linspace
np.linspace(1,2,5)#it will be diveded into 5 parts equally between 1 and 2

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
#creating ndarray with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,5,4)) #we have shape has 5 cross 4 matrix with 2 data

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
#creating ndarray with ones
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
#identinty matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#logspace-giving all the data in logscale
np.logspace(2,5,9)

array([   100.        ,    237.13737057,    562.34132519,   1333.52143216,
         3162.27766017,   7498.94209332,  17782.79410039,  42169.65034286,
       100000.        ])

In [44]:
#random
np.random.rand(3)#at every execution will be getting all the different random values
#rand- its like normal distribution from 0 to 1

array([0.0021072 , 0.23518703, 0.45419479])

In [49]:
np.random.randn(10)#rand-it is like a standard normal distribution gives a value from -1 to 1

array([-0.63289144, -0.49799714, -0.05705522,  0.67765418,  0.3618386 ,
        0.29023591, -0.17279159, -0.93991205, -0.14659354, -0.82269476])

In [53]:
np.random.randint(2,10,(4,4))#with the help of randint convert into matrix

array([[5, 8, 9, 7],
       [5, 5, 5, 2],
       [7, 7, 8, 2],
       [2, 6, 9, 5]])

In [57]:
#find min values from array
arr=np.array([
    
    [1,2,3],
    [1,4,6],
    [4,5,6]
    
       ])

arr.min()

1

In [58]:
#find max values from array
arr.max()

6

In [4]:
#Extraction rows and columns as per need,lets take example and solve it
arr=np.random.randint(4,100,(5,5))
#arr[3:,3:]
arr[:,1:3]

array([[69,  7],
       [63, 49],
       [81, 37],
       [56, 49],
       [45, 75]])

In [5]:
arr[:3,1:3]

array([[69,  7],
       [63, 49],
       [81, 37]])

In [ ]:
#can do basic operation with matrix addition,matrix multiplication,scalar multiplication,etc

In [8]:
#can't add or substract with different shape,lets see example
arr=np.zeros((2,5))
a=np.array([1,2,3])
arr+a

ValueError: operands could not be broadcast together with shapes (2,5) (3,) 

In [10]:
#Transpose
t=np.array([[1,2,3]])
t.T

array([[1],
       [2],
       [3]])

In [19]:
#find the square root 
arr=np.random.rand(5,4)
np.sqrt(arr)

array([[0.85386127, 0.12237667, 0.57526417, 0.82029717],
       [0.89001385, 0.85085412, 0.75257829, 0.58491533],
       [0.96867823, 0.85759118, 0.69218048, 0.46295512],
       [0.93209852, 0.99610096, 0.82000764, 0.95399298],
       [0.83774856, 0.81388152, 0.61887871, 0.84125554]])

In [20]:
#logarthmic values
np.log10(arr)

array([[-0.13722537, -1.82460275, -0.48026534, -0.17205757],
       [-0.10120647, -0.14028979, -0.24689662, -0.46581399],
       [-0.02764092, -0.13343939, -0.3195613 , -0.66892221],
       [-0.06107636, -0.00339328, -0.1723642 , -0.04090964],
       [-0.15377262, -0.17887763, -0.41678891, -0.15014413]])

In [21]:
#exponential values
np.exp(arr)

array([[2.07317048, 1.01508875, 1.39226076, 1.95988825],
       [2.20808287, 2.0625699 , 1.76186708, 1.40793761],
       [2.55572901, 2.08644704, 1.6146429 , 1.2390283 ],
       [2.38406653, 2.69720788, 1.95895768, 2.48457747],
       [2.01742641, 1.93944748, 1.46669395, 2.02934054]])

In [22]:
#by using random function you  and me will get same values
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])